name: Deploy to WordPress.org
on:
  push:
    branches: [ trunk ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #- name: Running NPM Install & Build For Gutenberg
      #  run: |
      #    npm install --silent && npm run build
      - name: Assets Update
        id: assets
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}